name: PGF-Claims
version: 5.3.1
api-version: 1.18
author: [bk, CrimsonDart]
main: net.pgfmc.claims.Main
description: implemets the Claims and Locking system
depend: [PGF-Core, PGF-Friends]
commands:
   inspector:
      aliases: [insp]
      usage: /<command>
      permission: teams.inspector.activate
      description: toggles Inspector mode if in Creative mode.
   editownable:
      aliases: [ewon]
      usage: /<command> <type> <value>
      permission: teams.inspector.edit
      description: Allows editing values of the latest inspected ownable.
   claimtp:
      aliases: [ctp]
      usage: /<command>
      permission: teams.inspector.claimtp
      description: Teleports the player to the claim they're in.
      